def calculator():
 print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
 print("")
 print("Welcome To the 2 way calculator")
 print("")
 print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
 print("")
 print("Choose your program")
 print("")
 print("1. Addition")
 print("2. Subtraction")
 print("3. Division")
 print("4. Multiplication")
 print("")
 program = int(input("What do you want to do today: "))
 print("") 
 print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")