print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
print("")
print("   Welcome To The Cashier Program")
print("")
print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
print("")
print("Choose what the customer bought:  ")
print("")
print("1. Burger & Chips")
print("2. Pizza")
print("3. Burger Only")
print("4. Chips Only")
print("5. Cool Drink")
print("")